### PR TITLE
New audio.lib footprints (SIP-8/9, Sanyo STK-4xx) and other KLC fixes

### PR DESCRIPTION
**Pull request by evanshultz**
As part of overhauling the audio library (https://github.com/KiCad/kicad-library/pull/1560), I needed a few footprints.

SIP-8
- http://www.thatcorp.com/datashts/THAT_2180-Series_Datasheet.pdf
- http://www.njr.com/semicon/PDF/package/SIP8_E.pdf
- THAT2180 and also NJR opamps
- I did not include body dimensions or pitch or other details in the footprint name (see discussion at https://github.com/KiCad/Housings_SIP.pretty/issues/6) so please comment on that.
- Also take a look at the pin 1 mark on F.Fab. 

I also made a new SIP-9, like the SIP-8 above but with fab lines and all that good stuff while I was at it. I didn't find a matching part online with a quick look, but it was in the library already so why not make it KLC compliant? I can also delete the old SIP-9 if you wish.

Sanyo_STK*
- http://datasheet.octopart.com/STK430-Sanyo-datasheet-107060.pdf
- There are two related packages
- Where dimensions are missing on one, I copied from the other as it looked correct

And, in the interest of leaving this a little better than how I found them, I updated the two existing STK* footprints. They didn't have fab lines, tags, wrong footprint name, etc. These may be On Semi specific so renaming for that reason, and others, should be suggested.
- http://www.onsemi.com/pub/Collateral/EN5227-D.PDF
- http://www.onsemi.com/pub/Collateral/EN6507-D.PDF

Image:
image

### CODE REVIEW

**Comment by poeschlr** [comment]
Should SIP-8 and SIP-9 include information about the pin pitch and the body size?
All of these packages are missing pin 1 markers. (At least in the screenshot)

Suggestion:
29744669-8a90333a-8a5e-11e7-9663-73aa8730541e

**Comment by evanshultz** [comment]
@poeschlr Thanks! SIP-8 and SIP-9 already have it as triangles on the left side. Sorry that was obscured in the screenshot. I'll do the others shortly.

**Comment by evanshultz** [comment]
@poeschlr Done! Anything else?
image

**Comment by evanshultz** [comment]
@poeschlr Anything else? Body size and pitch in SIP-8 and SIP-9 footprint names?

**Comment by evanshultz** [comment]
@poeschlr I added body size and pitch to the SIP packages. Can this be merged now?

**Comment by evanshultz** [comment]
@poeschlr Can this be merged?

**Comment by evanshultz** [comment]
@poeschlr Could you please take a look?

**Comment by evanshultz** [comment]
@jkriege2 Perhaps Rene is on vacation. Would you mind taking a look?

**Comment by poeschlr** [comment]
Not vacation but i have a deadline for a project that currently takes up all of my time. (I don't want to merge before i take a close look at the contribution.)

**Comment by evanshultz** [comment]
@poeschlr How long do you expect to be busy? This PR and https://github.com/KiCad/TO_SOT_Packages_THT.pretty/issues/26 are holding up the review and merge of https://github.com/KiCad/kicad-library/pull/1560, and I'd like to avoid that branch getting stale.

**Comment by poeschlr** [comment]
At least until Friday. After that i will need a few days off. (Currently i have about 5 to 6 hours of sleep per day. The rest is spend working.)

**Comment by evanshultz** [comment]
@poeshlr I appreciate wanting to make sure things are right before merging. Do you know when you'll have time for this?

**Comment by poeschlr** [comment]
Within the next few days. Currently i am too tired. (A few weeks too little sleep and way too much stress.)

**Comment by poeschlr** [comment]
I am back

So now for a more detailed review:

For the STK672-040-E the drill diameter might be a bit on the small side. Sadly the lead dimensions are given without listing their tolerances. Can we safely assume 0.5x0.4mm is the maximum size?
If it is the maximum size we can stay at 0.7mm it would give the pcb manufacturer 0.05mm drill size tolerance. But maybe increase to 0.75mm (would result in 0.05mm clearance all around. Similar to what you chose for SIL-8 and SIL-9.) 
If we are unsure about the lead size i would maybe even go with a 0.85mm drill. (Same drill as for SIP-8)

The same is true for STK672-080-E

screenshot from 2017-09-18 13-23-48

---

For the Sanyo_STK4xx-15_59.2x8.0mm_Pitch2.54mm the drill size is also on the small side. If you have 0.6+0.2mm lead (=0.8mm lead) you have zero tolerance for the pcb manufacturer. I would suggest at least 0.85mm drill size. (Would give the pcb manufactuer 0.05mm drill size tolerance in the worst case.)

The distance from the back to the pins should be 3.2mm it currently is 3.5mm
screenshot from 2017-09-18 13-53-32

The same applies for the second Sanyo footprint.

Is the name STK4xx correct? This footprint applies for 433, ... but not for 437, ...
Sadly not even STK43x would be correct. I don't know how we should handle this.

---

Edit: By the way this review took more than one hour. I hope you understand now why i had no time for it in the last few weeks.

**Comment by evanshultz** [comment]
@poeschlr 
Thanks for taking the time to check all the footprints!

I didn't touch the existing STK672 holes sizes, but I agree they're too small. Using IPC Level B, we need 0.2mm oversize so I enlarged their pads.

For the STK4xx footprints, I think the row of pins is correct. Zooming in, you will see 3.2mm appears to be to the back of the pins. Adding half of the nominal pin thickness, 0.3mm, gives the 3.5mm I used.
image

Also on those footprints, I missed the tolerance on the pads, so I was calculating with 0.6mm. Thanks for catching that. I should have used 0.8mm, the maximum diameter, and that's fixed.

Regarding their names, I used the dimensions to differentiate them and don't see a better way.

Anything else?

**Comment by evanshultz** [comment]
@poeschlr Do you see any other things to be fixed or is this ready to merge?

**Comment by poeschlr** [comment]
Looks good now.

**Pull request merged**
