### PR TITLE
Add SIP3

### PR DESCRIPTION
**Pull request by CarlPoirier**
screenshot_2017-04-12_22-03-22

Not sure why 10.2 is violated, though. I haven't looked at the script, but the info is in the screenshot.

Carl

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Please remove comma `,` from the tags

**Comment by jkriege2** [comment]
Shouldn't the name be a bit more specific (i.e. include manufacturer + component-series)? This seems to be for a specific series of switching regulators (right?)? I can imagine that there are many different SIP3-packages with different outlines ...

Best,
JAN

**Comment by CarlPoirier** [comment]
@jkriege2 I think we can keep it more general. I added the size to the footprint name.

**Comment by CarlPoirier** [comment]
The pin numbers were flipped, now they are corrected.

screenshot_2017-04-15_10-03-27

**Comment by SchrodingersGat** [comment]
@CarlPoirier can you please also rename the 3D model reference to match the new footprint name? :)

**Comment by CarlPoirier** [comment]
Good point. Done.

**Comment by SchrodingersGat** [comment]
Great work, thanks :)

**Pull request merged**
