### PR TITLE
[enh] add SIP4 Housing for Solid State Relais made by Sharp

### PR DESCRIPTION
**Pull request by pointhi**
Footprints for SSR made by Sharp.

Regarding PR: https://github.com/KiCad/kicad-library/pull/334

### CODE REVIEW

**Comment by pointhi** [comment]
I just noticed there is already a PR for this footprint: https://github.com/KiCad/Opto-Devices.pretty/pull/3

**Comment by pointhi** [comment]
**hold** I created a pcb, and it seems 2 pins are 2.54mm misalign. I have to recheck this and fix the footprints

**Comment by pointhi** [comment]
ok, the footprint is correct, but Sharp has different SIP-4 Footprints. (This one is for SSR like S202S01).
There is for example the S202T01 which has a wieder (but not so high) footprint.

**Comment by CarlPoirier** [comment]
Hi Thomas,

I suggest the _NoHole suffix, it's shorter. Besides that, it's great!

**Comment by pointhi** [comment]
good idea. Probably we also have to add something like `Series-S` or `SxxxSxx` to reflect the different SIP-4 footprints from Sharp

**Comment by pointhi** [comment]
@CarlPoirier done

**Comment by CarlPoirier** [comment]
Thank you, it's great.

**Pull request merged**
